"""add table account slot

Revision ID: f25ed8d19080
Revises: fbdb293056b2
Create Date: 2024-09-21 17:52:38.458223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f25ed8d19080"
down_revision: Union[str, None] = "fbdb293056b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_slot",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("subscription_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_slot")
    # ### end Alembic commands ###
