"""add table account slot

Revision ID: 4022f2669ccd
Revises: 85dd8193ae8c
Create Date: 2024-10-24 21:14:15.025069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4022f2669ccd"
down_revision: Union[str, None] = "85dd8193ae8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_slot",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("subscription_start", sa.DateTime(), nullable=False),
        sa.Column("subscription_end", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_slot")
    # ### end Alembic commands ###
