"""change logic subscription in table account slot

Revision ID: 4c56707e7525
Revises: f25ed8d19080
Create Date: 2024-09-22 11:36:46.825112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c56707e7525"
down_revision: Union[str, None] = "f25ed8d19080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_slot",
        sa.Column("subscription_start", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "account_slot",
        sa.Column("subscription_end", sa.DateTime(), nullable=False),
    )
    op.drop_column("account_slot", "subscription_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_slot",
        sa.Column(
            "subscription_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("account_slot", "subscription_end")
    op.drop_column("account_slot", "subscription_start")
    # ### end Alembic commands ###
