"""add table account

Revision ID: 355827a61c5c
Revises: 4022f2669ccd
Create Date: 2024-10-24 21:23:17.932539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "355827a61c5c"
down_revision: Union[str, None] = "4022f2669ccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("account_slot_id", sa.Integer(), nullable=True),
        sa.Column(
            "account_uuid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("avito_user_id", sa.BigInteger(), nullable=False),
        sa.Column("avito_client_id", sa.String(), nullable=False),
        sa.Column("avito_client_secret", sa.String(), nullable=False),
        sa.Column("avito_token", sa.String(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=False),
        sa.Column("account_status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_slot_id"], ["account_slot.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    # ### end Alembic commands ###
