"""add table account

Revision ID: f26afaa91f91
Revises: 4c56707e7525
Create Date: 2024-09-23 16:42:04.236389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f26afaa91f91"
down_revision: Union[str, None] = "4c56707e7525"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("account_slot_id", sa.Integer(), nullable=True),
        sa.Column("avito_user_id", sa.BigInteger(), nullable=False),
        sa.Column("avito_client_id", sa.String(), nullable=False),
        sa.Column("avito_client_secret", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "uuid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_slot_id"],
            ["account_slot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    # ### end Alembic commands ###
