"""delete uuid column and change name columns in table account

Revision ID: 4b201c055611
Revises: f26afaa91f91
Create Date: 2024-09-23 22:15:15.942219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b201c055611"
down_revision: Union[str, None] = "f26afaa91f91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("account_name", sa.String(), nullable=False))
    op.add_column("account", sa.Column("account_status", sa.Boolean(), nullable=False))
    op.drop_column("account", "status")
    op.drop_column("account", "name")
    op.drop_column("account", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "account",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "account",
        sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("account", "account_status")
    op.drop_column("account", "account_name")
    # ### end Alembic commands ###
