bot:
  token: "1234567890:AaBbCcDdEeFfGrOoShALlMmNnOoPpQqRrSs"

db:
  dsn: "driver://user:pass@localhost/dbname"
  is_echo: false

nats:
  dsn: "nats://127.0.0.1:4222"

logging:
  level: "WARNING"
  format: "%(filename)s:%(lineno)d #%(levelname)-8s [%(asctime)s] - %(name)s - %(message)s"
  filemode: "w"
  filename: "info.log"